version: 2
jobs:
  deploy:
    working_directory: ~/workspace
    docker:
      - image: cibuilds/hugo:0.53
    environment:
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:ae:d8:bb:39:1c:83:fd:f6:9b:64:6d:ea:a4:7e:b7"
      - run:
          name: deploy
          command: make deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: blog
