version: 2
jobs:
  deploy:
    working_directory: ~/workspace
    docker:
      - image: kurikenji/cihugo:latest
    environment:
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "52:55:11:79:d2:12:8d:73:5f:92:a5:23:fd:0f:95:ab"
      - run:
          name: deploy
          command: make deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: hugo
